#!/bin/sh
# Reassign ownership of the console to root, this should disallow
# assignment of console output to any random users's xterm
# $OpenBSD: TakeConsole.in,v 1.3 2023/11/10 18:49:21 matthieu Exp $
#
prefix="/usr/X11R6"
exec_prefix="${prefix}"

chown root:wheel /dev/console
chmod 622 /dev/console
if [ -c /dev/dri/card0 ]; then
    chown root:wheel /dev/dri/card0
fi
if [ -c /dev/dri/renderD128 ]; then
    chown root:wheel /dev/dri/renderD128
fi
${exec_prefix}/bin/sessreg -d -l $DISPLAY -u none $USER
